name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        docker-compose version

    # Pull and Run Docker Compose services
    - name: Pull and Run Docker Compose services
      run: |
        docker-compose -f docker-compose.yml pull
        docker-compose -f docker-compose.yml up -d
      env:
        DJANGO_SUPERUSER_USERNAME: admin
        DJANGO_SUPERUSER_PASSWORD: test1234
        DJANGO_SUPERUSER_EMAIL: admin@example.com

    # Set up Node and Install Dependencies
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install

    # Install Playwright Browsers
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    # Wait for services to be ready
    - name: Wait for services to be ready
      run: |
        until curl -s http://localhost:8000/ && curl -s http://localhost:3000/; do
          echo "Waiting for backend and frontend to be ready..."
          sleep 5
        done

    # Run Playwright tests
    - name: Run Playwright tests
      run: pnpm exec playwright test

    # Upload Playwright report as artifact
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
