name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      # Start the Docker services from docker-compose.yml as a background service in GitHub Actions
      docker:
        image: docker:stable
        options: --privileged
    steps:
    - uses: actions/checkout@v4
        # Set up Docker Compose
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Compose
      uses: docker/setup-qemu-action@v2

    - name: Pull and Run Docker Compose services
      run: |
        docker-compose -f docker-compose.yml pull
        docker-compose -f docker-compose.yml up -d
      env:
        DJANGO_SUPERUSER_USERNAME: admin
        DJANGO_SUPERUSER_PASSWORD: test1234
        DJANGO_SUPERUSER_EMAIL: admin@example.com
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
